### PR TITLE
Readme: Add instructions for dummies

### PR DESCRIPTION
**Pull request by expenses**
Hi @pablode, this plugin is awesome! I spent an embarrassing time working out how to install it properly though, as the cmake install step silently didn't do anything as I hadn't enabled the right build option. I thought I'd add some info to the readme for dummies like me on how to properly build the plugin and double-check that it's installed.

### CODE REVIEW

**Comment by pablode** [comment]
Hi - sorry for the late answer! Happy to merge the first part of the PR, but I'm conflicted about the usdview part. Basically, if the plugin is installed, you can just open glTF files with usdview. This knowledge does not seem to be obvious, but I'd rather prefer some external guide or SDF documentation to elaborate on that.

Additionally, the [USD debug env vars](https://lucascheller.github.io/VFX-UsdSurvivalGuide/core/profiling/debug.html) (SDF_FILE_FORMAT/PLUG_*) can be used for determine enablement. And again, I think "is a USD plugin enabled?" is a more general problem that should be clarified as part of the USD project, and not guc.

However, thanks for hinting on this problematic! (and perhaps this PR can serve as documentation as well)

**Comment by expenses** [comment]
Hi! Yeah I wrote this a while ago and I'm more comfortable with the USD Plugin system now. I'll take the second part out.

**Comment by expenses** [comment]
Done

**Comment by pablode** [comment]
Thanks for the contribution!

**Pull request merged**
